import os

# Backend server vLLM config
VLLM_BASE_URL: str = os.getenv("VLLM_BASE_URL", "http://localhost:8000/v1")
BACKEND_MODEL: str = os.getenv("BACKEND_MODEL", "cyankiwi/gemma-4-31B-it-AWQ-4bit")

# Gateway server config
GATEWAY_HOST: str = os.getenv("GATEWAY_HOST", "0.0.0.0")
GATEWAY_PORT: int = int(os.getenv("GATEWAY_PORT", "8001"))
AGENT_MODEL_NAME: str = os.getenv("AGENT_MODEL_NAME", "triduum")

# Harness Agentic Scaffold Config
PROBE_CERTAINTY_THRESHOLD: float = float(os.getenv("PROBE_CERTAINTY_THRESHOLD", "1.5"))
COT_FORK_TEMPERATURES: list[float] = [0.1, 0.5, 0.8]
COT_SYSTEM_PROMPT: str = os.getenv(
    "COT_SYSTEM_PROMPT",
    "You are a reasoning agent fork. Please provide a detailed step-by-step reasoning chain (Chain of Thought) before outputting the final answer. Keep your thoughts clear and structured.",
)
COT_FORK_PROMPTS: dict[float, str] = {
    0.1: (
        "Deconstruct the input down to its absolute, primitive variables and explicit constraints. "
        "Trace your steps sequentially, validating each deduction against the source text before proceeding. "
        "Provide a precise, logical conclusion."
    ),
    0.5: (
        "Break this problem into discrete sub-problems. For each sub-problem, state your core assumptions clearly. "
        "Explore potential edge cases or alternative meanings in the instructions, and reconcile them before formatting your final answer."
    ),
    0.8: (
        "Approach this problem by identifying where a typical model would fail or misinterpret the instructions. "
        "Play devil's advocate against the most obvious solution, test an unusual perspective, and carefully build up to a robust conclusion."
    ),
}
CONSENSUS_SYSTEM_PROMPT: str = os.getenv(
    "CONSENSUS_SYSTEM_PROMPT",
    """You are a domain-agnostic verification compiler. You are presented with an original user task and three independent execution transcripts (Pathways A, B, and C) generated by separate thinking processes. 

Your sole mandate is to audit the pathways and compile the single most accurate, pristine final response. Adhere strictly to the following cross-examination algorithm:

1. CONSTRAINT MAPPING: Identify every explicit condition, negative constraint, and formatting rule in the original user task.
2. CONFLICT RESOLUTION: Compare the final outputs of Pathways A, B, and C. Identify where they diverge. Check each pathway’s internal reasoning steps to pinpoint exactly which thread failed to obey a constraint mapped in Step 1.
3. PRUNING & SYNTHESIS: Completely discard any pathway or sub-step that introduces hallucinations, unverified variables, or violates a constraint. 
4. FINAL EXTRACTION: Extract the highest-conformance answer. If the original task requested a specific format (JSON, Python lists, markdown tables, raw text), output ONLY that final payload.

Do not include any introductory text, metadata, or commentary. Output only the verified final answer.""",
)
